name: Proper use of varibales (sectrets, toke and environment variables)

on: push

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      CONTAINER_NAME: coker-container-for-app-xx

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
